name: Testing Workflow

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    
#     services:
#       mysql:
#         image: mysql:latest
#         ports:
#           - 3306
#         env:
#           MYSQL_ALLOW_EMPTY_PASSWORD: yes
#         options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    
    strategy:
      matrix:
        #perl: ['5.14', '5.26', '5.30']
        perl: ['5.30']
        #env: [COVERALLS=true DB=mysql, COVERALLS=false DB=mysql, COVERALLS=false DB=sqlite]
        COVERALLS: [true, false]
        DB: [mysql, sqlite]
        container: ['tamaranaboulsi/test-repo:perl-5.014.004-custom']
        
        include:
          - perl: '5.30'
            container: 'tamaranaboulsi/test-repo:perl-5.030.004-custom'
            COVERALLS: false
            DB: mysql
            #env: COVERALLS=false DB=mysql
        exclude:
          - perl: '5.14'
            COVERALLS: false
            DB: mysql
            #env: COVERALLS=false DB=mysql
          - perl: '5.14'
            COVERALLS: true
            DB: mysql
            #env: COVERALLS=true DB=mysql
          - perl: '5.14'
            COVERALLS: true
            DB: sqlite
            #env: COVERALLS=true DB=sqlite
          - perl: '5.26'
            COVERALLS: false
            DB: sqlite
            #env: COVERALLS=false DB=sqlite
          - perl: '5.26'
            COVERALLS: false
            DB: mysql
            #env: COVERALLS=false DB=mysql
          - perl: '5.26'
            COVERALLS: true
            DB: sqlite
            #env: COVERALLS=false DB=mysql
          - perl: '5.30'
            COVERALLS: false
            DB: sqlite
            container: 'tamaranaboulsi/test-repo:perl-5.014.004-custom'
            #env: COVERALLS=false DB=sqlite
          - perl: '5.30'
            COVERALLS: false
            DB: mysql
            container: 'tamaranaboulsi/test-repo:perl-5.014.004-custom'
            #env: COVERALLS=false DB=mysql
          - perl: '5.30'
            COVERALLS: true
            DB: mysql
            container: 'tamaranaboulsi/test-repo:perl-5.014.004-custom'
            #env: COVERALLS=true DB=mysql
          - perl: '5.30'
            COVERALLS: true
            DB: sqlite
            container: 'tamaranaboulsi/test-repo:perl-5.014.004-custom'
            #env: COVERALLS=true DB=mysql
    
#     env:
#       AUTH_TOKEN: Ju069PzB8QZG3302emIhyCEEQfVfVsiXy0nGcR6hue+vW9nE82NnOEZHbZIwUCXEjUaZRMVQ31Em70Ky22OrLK4D59bs2ClH21u8URDGD/cn7JNPGWFrgxuaXQKMQrw72doeB0+w1+ShURtqM41vITjinyU3y34RZ1NcbDwYSZI=

    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Before Script
        run: |
          apt update && apt install sudo
          sudo apt update
          apt-get install -y default-mysql-server
#          apt-cache search mysql-server
#          sudo apt install mysql
#           apt-get install -y default-libmysqlclient-dev default-mysql-client
#           apt-get install -y libssl-dev sqlite3
#          apt-get install -y build-essential cpanminus git
      
#       - name: Perl ${{ matrix.perl }} Setup
#         uses: shogo82148/actions-setup-perl@v1
#         with:
#           perl-version: ${{ matrix.perl }}
      
      - name: Clone repos
        run: |
          git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
          git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
          git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
          git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
          git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git
      
      - uses: perl-actions/install-with-cpanm@v1
        name: Install dependencies
        with:
          cpanfile: "cpanfile"
          sudo: false
          verbose: true
          install: |
            Devel::Cover
            Devel::Cover::Report::Coveralls
            Test::Exception
            Moose
            Devel::Cycle
            Test::Warnings
            DBD::SQLite
            JSON
            namespace::autoclean
            Config::General
            DBIx::Class::Schema
      
      - name: Copy mysql/sqlite conf files
        run: |
          cp travisci/MultiTestDB.conf.actions.mysql modules/t/MultiTestDB.conf.mysql
          cp travisci/MultiTestDB.conf.actions.SQLite modules/t/MultiTestDB.conf.SQLite
          cp travisci/testdb.conf.actions.mysql testdb.conf.mysql
          cp travisci/testdb.conf.actions.SQLite testdb.conf.SQLite
      
      - name: Configure mysql
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: |
          service mysql start
          mysql -e "CREATE USER 'github'@'%'" -u root -h localhost
          mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'github'@'%'" -u root -h localhost
          mysql -e "SET GLOBAL local_infile=1" -u root -h localhost
      
      - name: Run Test Suite
        env:
          DB: ${{ matrix.DB }}
          COVERALLS: ${{ matrix.COVERALLS }}
          USER: 'github'
        run: ./travisci/harness.sh
