name: Testing Workflow (with containers)

on:
  push:
    branches:
      - github_actions_testing

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    strategy:
      matrix:
        perl: ['5.14', '5.26', '5.30']
        coveralls: [true, false]
        database: [mysql, sqlite]
        container: ['ubuntu:trusty']
#         container: ['tamaranaboulsi/test-repo:perl-5.014.004-custom']
        include:
          - perl: '5.30'
#             container: 'tamaranaboulsi/test-repo:perl-5.030.004-custom'
            container: 'ubuntu:focal'
            coveralls: false
            database: mysql
        exclude:
          - perl: '5.14'
            coveralls: true
          - perl: '5.14'
            coveralls: false
            database: mysql
          - perl: '5.26'
            coveralls: false
          - perl: '5.26'
            coveralls: true
            database: sqlite
          - perl: 5.30
            coveralls: true
          - perl: '5.30'
            container: 'ubuntu:trusty'
          - perl: 5.30
            coveralls: false
            database: sqlite
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Before script
        run: |
          apt update && apt install sudo
          sudo apt-get update
          sudo apt-get install xz-utils

      - name: Set up perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          
#       - name: Install mysql
#         run: |
#           apt-get install -y mysql-server
#           mysql -V
#          apt-get install -y mysql-server
#          apt-get install -y default-mysql-server
          

#       - name: Install dependencies
#         run: |
#           cpanm -v --sudo --installdeps --notest . --with-all-features
#          cpanm -n --sudo Devel::Cover Devel::Cover::Report::Coveralls Test::Exception Moose Devel::Cycle Test::Warnings
#          cpanm -n --sudo DBD::SQLite JSON
      
#       - name: Clone repos
#         run: |
#           git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
#           git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-io.git
#           git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
#           git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
#           git clone -b release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git
      
      - uses: perl-actions/install-with-cpanm@v1
        name: Install dependencies
        with:
          cpanfile: "cpanfile"
          sudo: false
          verbose: true
#           install: |
#             Devel::Cover
#             Devel::Cover::Report::Coveralls
#             Test::Exception
#             Moose
#             Devel::Cycle
#             Test::Warnings
#             DBD::SQLite
#             JSON
#             namespace::autoclean
#             Config::General
#             DBIx::Class::Schema
#             Text::Glob
#             Text::CSV
#             SQL::Translator
      
#       - name: Copy mysql/sqlite conf files
#         run: |
#           cp travisci/MultiTestDB.conf.actions_containers.mysql modules/t/MultiTestDB.conf.mysql
#           cp travisci/MultiTestDB.conf.actions.SQLite modules/t/MultiTestDB.conf.SQLite
#           cp travisci/testdb.conf.actions_containers.mysql testdb.conf.mysql
#           cp travisci/testdb.conf.actions.SQLite testdb.conf.SQLite
#           cp travisci/edited_runtests.pl ensembl-test/scripts/runtests.pl
      
#       - name: Configure mysql
#         run: |
#           service mysql start
#           mysql -e "CREATE USER 'github'@'%'" -u root -h localhost
#           mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'github'@'%'" -u root -h localhost
#           mysql -e "SET GLOBAL local_infile=1" -u root -h localhost
      
#       - name: Run Test Suite
#         env:
#           DB: ${{ matrix.database }}
#           COVERALLS: false
#           USER: 'github'
#         run: ./travisci/harness.sh

#       - if: ${{ matrix.COVERALLS }}
#         name: Coveralls
#         uses: coverallsapp/github-action@master
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
