name: Testing Workflow

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    
    strategy:
      matrix:
        perl: ['5.14', '5.26', '5.30']
        env: [COVERALLS=true DB=mysql, COVERALLS=false DB=mysql, COVERALLS=false DB=sqlite]
        container: ['tamaranaboulsi/test-repo:perl-5.014.004-custom']
        
        include:
          - perl: '5.30'
            container: 'tamaranaboulsi/test-repo:perl-5.030.004-custom'
            env: COVERALLS=false DB=mysql
        exclude:
          - perl: '5.14'
            env: COVERALLS=false DB=mysql
          - perl: '5.14'
            env: COVERALLS=true DB=mysql
          - perl: '5.26'
            env: COVERALLS=false DB=sqlite
          - perl: '5.26'
            env: COVERALLS=false DB=mysql
          - perl: '5.30'
            container: 'tamaranaboulsi/test-repo:perl-5.014.004-custom'
            env: COVERALLS=false DB=sqlite
          - perl: '5.30'
            container: 'tamaranaboulsi/test-repo:perl-5.014.004-custom'
            env: COVERALLS=false DB=mysql
          - perl: '5.30'
            container: 'tamaranaboulsi/test-repo:perl-5.014.004-custom'
            env: COVERALLS=true DB=mysql

    steps:
      - name: Checkout
        uses: actions/checkout@master
