name: Testing Workflow (ubuntu versions)

on:
  push:
    branches:
      - github_actions_testing

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    strategy:
      matrix:
        perl: ['5.14', '5.26', '5.30']
        coveralls: [true, false]
        database: [mysql, sqlite]
        container: ['ubuntu:trusty']
        include:
          - perl: '5.30'
            container: 'ubuntu:focal'
            coveralls: false
            database: mysql
        exclude:
          - perl: '5.14'
            coveralls: true
          - perl: '5.14'
            coveralls: false
            database: mysql
          - perl: '5.26'
            coveralls: false
          - perl: '5.26'
            coveralls: true
            database: sqlite
          - perl: 5.30
            coveralls: true
          - perl: '5.30'
            container: 'ubuntu:trusty'
          - perl: 5.30
            coveralls: false
            database: sqlite

    services:
      mysql:
        image: mysql:latest
        env:
#           MYSQL_ROOT_PASSWORD: secret
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - '3306:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Environment setup
        run: |
          apt update && apt install sudo
          sudo apt-get update
          sudo apt-get install -y xz-utils
          sudo apt-get install -y build-essential
          sudo apt-get install -y git
          sudo apt-get install -y mysql-client
          sudo apt-get install -y libdbd-mysql-perl
#          ldd --version
      
      - name: Set up perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      
      - run: sudo apt-get install -y cpanminus
      
      - name: Install dependencies
        run: |
          sudo cpanm -v --installdeps --notest . --with-all-features
          sudo cpanm -n Net::SSLeay --force
          sudo cpanm -n Devel::Cover Devel::Cover::Report::Coveralls Test::Exception Moose Devel::Cycle Test::Warnings
          sudo cpanm -n DBD::SQLite JSON
      
#       - name: Before
#         run: mysql --version
#           sudo apt-get -y install lsb-release
#           lsb_release -a
#           perl --version
#           mysqladmin ping
#          mysqld --version
#          mysqladmin -V
